A small demo for most of numpy functions. that will help you to understand the basics behind them. Thank you.

In [1]:
import numpy as np

In [3]:
# 1. creating One-D array nd printing values
arr = np.array([1,4,3])

In [4]:
print(arr)

[1 4 3]


In [5]:
# 2. Printing the type of array
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
# 3. Creating 2-D array and printing
arr2 = np.array([(1,2,3),(4,5,6)])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [11]:
# 4. printing the type of above np.array
print(type(arr2))

<class 'numpy.ndarray'>


In [12]:
# 5. creating an array and finding its type.
arr3 = np.array([1,4,3])
print(arr3.ndim)

1


In [14]:
# 6. finding the byte size oof the above array
print(arr3.itemsize)

4


In [17]:
# 7. finding datatype  of each element in the above array
print(arr3.dtype)

int32


In [18]:
# 8. finding the size of the above numpy array.
print(arr3.size)

3


In [24]:
# 9. Creating an array with np.zeros function
arr4 = np.zeros([3,3])
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# 10. Creating an array with np.ones.
arr5 = np.ones([3,3])
print(arr5)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# 11. Finding the shape for the below numpy array.
arr6 = np.array([(1,2,3),(4,5,6)])
print(arr6.shape)

(2, 3)


In [33]:
# 12. Finding and reshhapng theabove array with [4,2].
# NOTE : Reshaping a numpy array has certain rules to follow. 
arr7 = np.array([(1,2,3),(4,5,6)])
np.reshape(arr7,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
# 13. Finding the slice of an array for a[0:,2]
# NOTE : Reshaping a numpy array has certain rules to follow. 
arr8 = np.array([(1,2,3),(4,5,6)])
print(arr8)
print(arr8[:,2])

[[1 2 3]
 [4 5 6]]
[3 6]


In [37]:
# 14. printing linspace for the values (1,2,5).
print(np.linspace(1,2,5))

[1.   1.25 1.5  1.75 2.  ]


In [46]:
# 15. Finding Sum, max and min of an array for the following vales [(1,2,3),(3,4,5)].
arr9 = np.array([(1,2,3),(3,4,5)])
print(arr9)
print(' The sum of above Array is : ', arr9.sum())
print(' The min of above Array is : ', arr9.min())
print(' The max of above Array is : ', arr9.max())


[[1 2 3]
 [3 4 5]]
 The sum of above Array is :  18
 The min of above Array is :  1
 The max of above Array is :  5


In [47]:
# 16. Finding row wise and column wise sum of array.
arr10 = np.array([(1,2,3),(3,4,5)])
print(sum(arr10))

[4 6 8]


In [49]:
# 17. Finding transpose of an array.
arr11 = np.array([(1,2,3),(3,4,5),(9,6,0)])
print(arr11.T)

[[1 3 9]
 [2 4 6]
 [3 5 0]]


In [52]:
# 18. Finding row wise sort and column wise sort.
arr12 = np.array([(1,4,2),(3,4,6),(0,-1,5)])
np.sort(arr12)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [61]:
# 19. Finding the Horizontal split and Vertical split. 
arr13 = np.array([(1,3,5,7,9,11),(2,4,5,8,10,12)])
print('verirical split : ',np.vsplit(arr13,1)) # Here, (arr13,1) --> 1 represents the parts in which you wanna distribute the array.(division of the main array in '1' verical parts.)
print('Horizontal split : ',np.hsplit(arr13,1))

verirical split :  [array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  5,  8, 10, 12]])]
Horizontal split :  [array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  5,  8, 10, 12]])]


In [66]:
# 20. Finding the Vstack and Hsrack for the following Values:
arr14 = np.array([(1,2,3),(3,4,5)])
arr15 = np.array([(1,2,3),(3,4,5)])
print('Hstack: ',np.hstack((arr14,arr15)), '\n')
print('Vstack: ',np.vstack((arr14,arr15)))

Hstack:  [[1 2 3 1 2 3]
 [3 4 5 3 4 5]] 

Vstack:  [[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
